stages:
  - deploy

deploy_to_ec2:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh git docker-compose
  script:
    - mkdir -p ~/.ssh
    - echo "$EC2_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@18.234.31.134 << 'EOF'
      cd lab-10.3
      git pull origin main
      docker-compose up -d --build
      EOF
  only:
    - main

