version: '3.8'

services:
  app:
    build: .
    #image: nest-docker
    container_name: nest-docker
    ports:
      - "3000:3000"
    volumes:
      - /storage:/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=0
    depends_on:
      - db

  db:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      
volumes:
  mongo_data:
